apiVersion: v2
name: cryptgeon
description: A Helm chart for Kubernetes
maintainers:
  - name: swibrow
    email: sam.wibrow@gmail.com
type: application
version: 0.3.0
appVersion: "2.9.1"

dependencies:
  - name: valkey
    version: 0.9.3
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
