apiVersion: v2
name: cryptgeon
description: A Helm chart for Kubernetes
maintainers:
  - name: swibrow
    email: foo@bar.baz
type: application
version: 0.1.1
appVersion: "2.4.0"

dependencies:
  - name: redis
    version: 18.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
