apiVersion: v2
name: cryptgeon
description: A Helm chart for Kubernetes
maintainers:
  - name: swibrow
    email: sam.wibrow@gmail.com
type: application
version: 0.2.0
appVersion: "2.9.1"

dependencies:
  - name: valkey
    version: 3.0.9
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
