apiVersion: v2
name: cryptgeon
description: A Helm chart for Kubernetes
maintainers:
  - name: swibrow
    email: sam.wibrow@gmail.com
type: application
version: 0.1.3
appVersion: "2.4.0"

dependencies:
  - name: redis
    version: 19.1.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
